amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: ${aws.access.key.id}
  secretKey: ${aws.access.key.secret}
  bucketName: ${aws.s3.audio.bucket}
#spring:
#  rabbitmq:
#    port: 1234
#---
#spring:
#  rabbitmq:
#    port: 1235
#---
#spring:
#  rabbitmq:
#    port: 1234
#---
#spring:
#  rabbitmq:
#    port: 1234
#---
#spring:
#  profiles: dev
#  rabbitmq:
#    port: 4651